# Name:- Sonali Ganesh Magar
# Class:- IF5K
# Task:- Homework3

In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
#Returns True if all elements are True(non-zero)
np.all(arr) 
np.any(arr) 

np.True_

In [11]:
#Checks if two arrays are element-wise equal within a tolerance.
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0000001, 3.0])
np.allclose(a, b) 

True

In [12]:
#Returns the maximum value.
np.amax(arr, axis=0)

array([10, 11, 12])

In [13]:
#Returns the minimum value.
np.amin(arr, axis=0)

array([1, 2, 3])

In [15]:
#Appends values to the end of the array.
np.append(arr, [[13, 14, 15]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
#Returns the index of the maximum value.
np.argmax(arr)

np.int64(11)

In [18]:
#Returns the index of the minimum value.
np.argmin(arr)

np.int64(0)

In [19]:
#Returns indices that would sort the array.
a = np.array([9, 3, 7, 1])
np.argsort(a) 

array([3, 1, 2, 0])

In [21]:
#Converts an array to a string representation.
np.array2string(arr)

'[[ 1  2  3]\n [ 4  5  6]\n [ 7  8  9]\n [10 11 12]]'

In [22]:
#Checks if two arrays have the same shape and elements.
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.array_equal(a, b) 

True