# Name:- Sonali Ganesh Magar
# Class:- IF5K
# Task:- Homework3

In [22]:
import numpy as np

In [23]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [24]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
#Returns True if all elements are True(non-zero)
np.all(arr) 
np.any(arr) 

np.True_

In [26]:
#Checks if two arrays are element wise equal within a tolerance.
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0000001, 3.0])
np.allclose(a, b) 

True

In [27]:
#Returns the maximum value.
np.amax(arr, axis=0)

array([10, 11, 12])

In [28]:
#Returns the minimum value.
np.amin(arr, axis=0)

array([1, 2, 3])

In [29]:
#Appends values to the end of the array.
np.append(arr, [[13, 14, 15]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [30]:
#Returns the index of the maximum value.
np.argmax(arr)

np.int64(11)

In [31]:
#Returns the index of the minimum value.
np.argmin(arr)

np.int64(0)

In [32]:
#Returns indices that would sort the array.
a = np.array([9, 3, 7, 1])
np.argsort(a) 

array([3, 1, 2, 0])

In [33]:
#Converts an array to a string representation.
np.array2string(arr)

'[[ 1  2  3]\n [ 4  5  6]\n [ 7  8  9]\n [10 11 12]]'

In [34]:
#Checks if two arrays have the same shape and elements.
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.array_equal(a, b) 

True

In [41]:
#returns evenly spaced values over a specified interval.
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [36]:
#Calculates Sum
print(np.sum([1, 2, 3]))

6


In [37]:
##Calculates mean
print( np.mean([1, 2, 3, 4]))

2.5


In [38]:
##Calculates median
print(np.median([1, 3, 5, 7]))

4.0


In [39]:
#Calculates Standard Deviation
print(np.std([1, 2, 3, 4]))

1.118033988749895


In [40]:
#do not returns duplicate items item
arr = np.unique([1, 2, 2, 3])
print(arr)

[1 2 3]
